name: Run CD
run-name: ${{ github.actor }} is running GitHub Actions 🚀
on:
  push:
    branches:
      - main
env:
  SERVICE_ACCOUNT_KEY: ${{ secrets.SERVICE_ACCOUNT_KEY }}
  SLACK_APP_TOKEN: ${{ secrets.SLACK_APP_TOKEN }}
  SLACK_BOT_TOKEN: ${{ secrets.SLACK_BOT_TOKEN }}
  SLACK_SIGNING_SECRET: ${{ secrets.SLACK_SIGNING_SECRET }}
jobs:
  cd:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Set up Node.js
        uses: actions/setup-node@v4
        with:
          node-version: '20.x'

      - name: Install dependencies
        run: npm install
        working-directory: functions

      - name: Lint code
        run: npm run lint
        working-directory: functions

      - name: Format code
        run: npm run format
        working-directory: functions

      - name: Build project
        run: npm run build
        working-directory: functions

      - name: Run tests
        run: npm test
        working-directory: functions

      - name : Install Firebase CLI
        run: npm install -g firebase-tools
      - name: Print environment variables
        run: env

      - name: Deploy to Firebase
        env:
          FIREBASE_TOKEN: ${{ secrets.FIREBASE_TOKEN }}
          SERVICE_ACCOUNT_KEY: ${{ secrets.SERVICE_ACCOUNT_KEY }}
          SLACK_APP_TOKEN: ${{ secrets.SLACK_APP_TOKEN }}
          SLACK_BOT_TOKEN: ${{ secrets.SLACK_BOT_TOKEN }}
          SLACK_SIGNING_SECRET: ${{ secrets.SLACK_SIGNING_SECRET }}
        run: firebase deploy --only functions
